"""empty message

Revision ID: 011d8c920efe
Revises: 00d4c6a29a5d
Create Date: 2022-05-10 23:13:39.951762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011d8c920efe'
down_revision = '00d4c6a29a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
