"""empty message

Revision ID: 034c86535b77
Revises: 57ffdf7d3b6f
Create Date: 2022-05-12 11:01:45.667737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034c86535b77'
down_revision = '57ffdf7d3b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
