"""established relationship between goal and tasks

Revision ID: 07116c5880a9
Revises: c185c79f2cc0
Create Date: 2022-05-11 19:53:12.996323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07116c5880a9'
down_revision = 'c185c79f2cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
