"""empty message

Revision ID: 0a337e1b20d1
Revises: 761f4c697478
Create Date: 2022-05-12 09:03:18.517298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a337e1b20d1'
down_revision = '761f4c697478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'title',
               existing_type=sa.INTEGER(),type_=sa.VARCHAR,
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
