"""establish relationship

Revision ID: 139722841f44
Revises: 3824357d18a8
Create Date: 2022-05-10 13:30:24.534462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139722841f44'
down_revision = '3824357d18a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goal', 'task', ['task_id'], ['task_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goal', type_='foreignkey')
    op.drop_column('goal', 'task_id')
    # ### end Alembic commands ###
