"""empty message

Revision ID: 169136ea9374
Revises: e233315c8a70
Create Date: 2022-05-11 16:00:39.774392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169136ea9374'
down_revision = 'e233315c8a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
