"""empty message

Revision ID: 18957d7eb2f9
Revises: f523f252ac5d
Create Date: 2022-05-12 14:00:36.626394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18957d7eb2f9'
down_revision = 'f523f252ac5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
