"""add Goal model

Revision ID: 196842bc206c
Revises: 5b4ee81cb0e1
Create Date: 2022-05-06 12:45:47.996908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196842bc206c'
down_revision = '5b4ee81cb0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
