"""empty message

Revision ID: 284867c8e87d
Revises: 15ece1648808
Create Date: 2022-05-11 18:07:06.766210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284867c8e87d'
down_revision = '15ece1648808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###
