"""empty message

Revision ID: 29e76300924d
Revises: 95d21cd33d1c
Create Date: 2022-05-11 14:23:41.235941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e76300924d'
down_revision = '95d21cd33d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###
