"""empty message

Revision ID: 2e5e09dec829
Revises: 77eec873ce8b
Create Date: 2022-05-12 21:20:49.326076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5e09dec829'
down_revision = '77eec873ce8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
