"""One to Many relationship Task Goals

Revision ID: 30819a148113
Revises: 0de5eef122a9
Create Date: 2022-05-11 21:37:40.206375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30819a148113'
down_revision = '0de5eef122a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
