"""empty message

Revision ID: 331812ea27ac
Revises: f7b09bb339e1
Create Date: 2022-05-11 22:43:30.586003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331812ea27ac'
down_revision = 'f7b09bb339e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
