"""empty message

Revision ID: 342fd3522a5f
Revises: 2a4f296d0527
Create Date: 2022-05-08 14:48:09.706233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342fd3522a5f'
down_revision = '2a4f296d0527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
