"""add goal model

Revision ID: 3824357d18a8
Revises: 2bc7b4a190e3
Create Date: 2022-05-09 15:08:16.940497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3824357d18a8'
down_revision = '2bc7b4a190e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
