"""adds title column to Goal model

Revision ID: 454c55886326
Revises: c4b28b567d49
Create Date: 2022-05-11 10:21:04.021145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454c55886326'
down_revision = 'c4b28b567d49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
