"""empty message

Revision ID: 48907f71ca3c
Revises: 9b90ac0681f9
Create Date: 2022-05-26 18:03:18.075104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48907f71ca3c'
down_revision = '9b90ac0681f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('goal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###
