"""empty message

Revision ID: 52472d85a18a
Revises: 9ef25ada1cd2
Create Date: 2022-05-07 15:05:56.690097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52472d85a18a'
down_revision = '9ef25ada1cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
