"""Add title attribute to Goal model

Revision ID: 6f6a3b0aa0e1
Revises: 44ebda0e7dc8
Create Date: 2022-05-11 15:15:36.569363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6a3b0aa0e1'
down_revision = '44ebda0e7dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
