"""empty message

Revision ID: 710de958d23c
Revises: e3b3d6314e44
Create Date: 2022-05-14 14:26:48.815609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710de958d23c'
down_revision = 'e3b3d6314e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
