"""add goal

Revision ID: 728082a946ce
Revises: 8517a1480ffe
Create Date: 2022-05-10 22:04:11.017043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728082a946ce'
down_revision = '8517a1480ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
