"""empty message

Revision ID: 761f4c697478
Revises: 7af4d1b0d3d6
Create Date: 2022-05-12 02:06:09.512339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761f4c697478'
down_revision = '7af4d1b0d3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('task', 'id')
    # ### end Alembic commands ###
