"""empty message

Revision ID: 79628078bf82
Revises: f2a9e701628c
Create Date: 2022-05-07 19:11:44.646148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79628078bf82'
down_revision = 'f2a9e701628c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
