"""empty message

Revision ID: 831c0c4fbf59
Revises: d642435c108f
Create Date: 2022-05-10 17:51:44.377787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831c0c4fbf59'
down_revision = 'd642435c108f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
