"""empty message

Revision ID: 83afdb28ef84
Revises: dd11b33d419f
Create Date: 2022-05-12 09:56:38.508405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83afdb28ef84'
down_revision = 'dd11b33d419f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
