"""empty message

Revision ID: 84424732173e
Revises: ecf3abb8d480
Create Date: 2022-05-11 13:29:09.871904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84424732173e'
down_revision = 'ecf3abb8d480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
