"""make goal

Revision ID: 848028ca0487
Revises: 88f1e2121c63
Create Date: 2022-05-13 01:16:30.304978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848028ca0487'
down_revision = '88f1e2121c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('goal', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'title')
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###
