"""empty message

Revision ID: 861f27daf514
Revises: cf50ea1d4d64
Create Date: 2022-05-06 16:19:47.990817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861f27daf514'
down_revision = 'cf50ea1d4d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
