"""connect Goal and Task in one-to-many relationship

Revision ID: 894323ac7750
Revises: 2d34ef208110
Create Date: 2022-05-09 23:10:21.948139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894323ac7750'
down_revision = '2d34ef208110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
