"""empty message

Revision ID: 89794104d6fd
Revises: 284867c8e87d
Create Date: 2022-05-11 18:42:15.513790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89794104d6fd'
down_revision = '284867c8e87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###
