"""empty message

Revision ID: 8cda29a784b7
Revises: 0c5da718e164
Create Date: 2022-05-09 12:19:56.673365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cda29a784b7'
down_revision = '0c5da718e164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
