"""empty message

Revision ID: 8e4074903e70
Revises: fc0893eb74cb
Create Date: 2022-05-05 17:57:21.654055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4074903e70'
down_revision = 'fc0893eb74cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
