"""Title and description nullable=False

Revision ID: 970f04ee6541
Revises: 18d7a8b233e7
Create Date: 2022-05-06 21:31:30.079731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970f04ee6541'
down_revision = '18d7a8b233e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
