"""empty message

Revision ID: 986f48237e43
Revises: 3a0342042892
Create Date: 2022-05-10 21:44:34.614465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986f48237e43'
down_revision = '3a0342042892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
