"""empty message

Revision ID: 9953dcff842a
Revises: 0a337e1b20d1
Create Date: 2022-05-12 12:36:44.338506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9953dcff842a'
down_revision = '0a337e1b20d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('task', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###
