"""empty message

Revision ID: aac5410ddce2
Revises: 6ba865cd7c5b
Create Date: 2022-05-06 20:01:44.507496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac5410ddce2'
down_revision = '6ba865cd7c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.Integer(), nullable=False))
    op.drop_column('task', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###
