"""empty message

Revision ID: b5ea4a589733
Revises: d183f5b19cdb
Create Date: 2022-05-10 14:34:46.571432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ea4a589733'
down_revision = 'd183f5b19cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goal_task_id_fkey', 'goal', type_='foreignkey')
    op.drop_column('goal', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('goal_task_id_fkey', 'goal', 'task', ['task_id'], ['task_id'])
    # ### end Alembic commands ###
