"""empty message

Revision ID: bc911061b047
Revises: 8bc5461024b2
Create Date: 2022-05-10 21:31:09.129421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc911061b047'
down_revision = '8bc5461024b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'goal_name')
    # ### end Alembic commands ###
