"""adds Goal model

Revision ID: d3cc08e0cf60
Revises: e4b14a16c627
Create Date: 2022-05-11 15:05:23.558766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cc08e0cf60'
down_revision = 'e4b14a16c627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'goal_title')
    # ### end Alembic commands ###
