"""empty message

Revision ID: e66361cb0cb1
Revises: d0dcc64964c0
Create Date: 2022-05-07 19:28:12.900453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66361cb0cb1'
down_revision = 'd0dcc64964c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_complete')
    op.drop_column('tasks', 'completed_at')
    # ### end Alembic commands ###
