"""empty message

Revision ID: ec279ccb6352
Revises: 29e76300924d
Create Date: 2022-05-11 14:24:19.722953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec279ccb6352'
down_revision = '29e76300924d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_task_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_task_id_fkey', 'task', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###
