"""changed attribute name on goal title

Revision ID: fbdec80a71e0
Revises: 1f387874348e
Create Date: 2022-05-11 18:58:52.517830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdec80a71e0'
down_revision = '1f387874348e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('goal', 'goal_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
